services:
  db1:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: tavel-planning-db
    ports:
      - "1434:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=TravelApp2026!#
